name: Main build

on:
  push:
    branches:
      - main
  release:
    types:
      - published

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - run: echo "running main build"
  e2e-tests:
    needs: [build]
    uses: ./.github/workflows/e2e.yaml
