on:
  workflow_dispatch:
  merge_group:
    types: [checks_requested]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - run: echo "Running merge group/workflow dispatch ${GITHUB_SHA}"

  e2e-tests:
    uses: ./.github/workflows/e2e.yaml
    needs: [build]

