name: Pull request build

on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - synchronize
      - reopened
      - ready_for_review

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - run: echo "Running PR build"

  e2e-tests:
    if: github.event.pull_request.draft == false
    uses: ./.github/workflows/e2e.yaml
    needs: [build]
